# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
    displayName: 'Install Node.js'

- script: |
    npm ci
    npm run build
    npm run export
  displayName: 'Build project'

- task: CopyFiles@2
  inputs:
    contents: 'out/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy output to staging'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Artifact'